# Generated by Django 3.2.16 on 2022-12-16 11:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.TextField(max_length=100)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MaxLengthValidator(60), django.core.validators.MinLengthValidator(18)])),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('profilepicture', models.URLField(blank=True, null=True, verbose_name='Profile Picture')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default=1, max_length=10)),
                ('model', models.CharField(max_length=20, null=True)),
                ('year', models.DateField(max_length=2049, null=True)),
                ('imageurl', models.URLField()),
                ('price', models.IntegerField(null=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='CarCollections_app.profile')),
            ],
        ),
    ]
