# Generated by Django 3.2.16 on 2022-12-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollections_app', '0002_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.URLField(blank=True, default=1, verbose_name='Profile Picture'),
            preserve_default=False,
        ),
    ]
