# Generated by Django 3.2.16 on 2022-12-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollections_app', '0004_alter_profile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepicture',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
