# Generated by Django 3.2.16 on 2022-12-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollections_app', '0009_alter_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(max_length=2049, null=True),
        ),
    ]
