# Generated by Django 3.2.16 on 2022-12-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarCollections_app', '0010_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(blank=True, default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
